name: Called Workflow

on:
    workflow_call: 

jobs:
    print_secret:
        runs-on: ubuntu-latest

        steps:
            - name: Display Token
              env:
                ENV_SECRET: ${{ secrets.BETA_TOKEN }}  
              run: |
                echo "ugjg"

