name: Called Workflow

on:
    workflow_call: 

jobs:
    print_secret:
        runs-on: ubuntu-latest

        steps:
            - name: Display Token
              run: |
                echo ${{secrets.BETA_TOKEN}}
